[build]
  command = "npm run build"
  ## publish = ".next" # Commented out to let plugin handle it


[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[context.production]
  environment = { NODE_ENV = "production" }
